Adds germplasm collection panel
UofS-Pulse-Binfo/uofspb_germplasm pull request #7
Opened 2022-03-02 18:26 UTC by reynoldtan

This PR will add germplasm collection panel (list exportable to a csv file) to study/experiment content.

## Metadata

 - Issue #

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

1. Modified local__project_germcollection field to
a. Fetch germplasm/stock collection of a study
b. Create table markup showing germplasm list based on the set collection in the field settings panel.
c. Update install file to implement a hook schema and setup backend used to map collection to a study.
 
## Dependencies

## Testing?

- [ ] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

1. Clone module and switch branch to project-collection-field.
2. Install and enable module - germcollection
3. Modify Study Tripal Content Type and add fields germplasm collection (local: project germcollection)
![Screen Shot 2022-03-02 at 12 16 28 PM](https://user-images.githubusercontent.com/15472253/156423323-8a23bc2d-19dc-4d47-bf7f-cc1ce9e42b90.png)
Click check for new field link if fields have not been added previously.
4. Click save. Note: before saving make sure fields are not in the disabled list.
5. Modify an existing study and set the value under Germplasm field in the update study page.
![Screen Shot 2022-03-02 at 12 19 41 PM](https://user-images.githubusercontent.com/15472253/156423850-3979fab2-258b-477b-9d29-694c8ade0546.png)
6. Click save and reload study page to view germplasm collection list.
![Screen Shot 2022-03-02 at 12 20 57 PM](https://user-images.githubusercontent.com/15472253/156424271-177e4d0d-1430-46c6-bb1d-a9bdcb2f7c10.png)

**Additional configuration:**
1. To view and export germplasm collection, user must be logged in and given permission to view and download germplasm collection.

2022-03-03 17:07 UTC, ruobinLiu commented
I have the add germplasm collection panel tested on multiple projects, it works as expected overall. Except sometimes, the germplasm only shows up when a page is refreshed through  "put cursor beside the url link", then "click enter button".

2022-03-04 20:13 UTC, laceysanderson requested changes
See further comments on the code review -Overall good though :-)

This field should also include the name of the germplasm collection and a link to a page (although we're still working on those so ensure it only shows if the page exists as always :-) ). The idea is that once this field is in place the old text field addition of stock collection would go away.

With this change, we will always want the name + number of germplasm shown regardless of permission. If no permission though the download link would be disabled and no list would be shown.

2022-03-04 20:13 UTC, laceysanderson commented on germcollection/api/germcollection.api.inc
> + *   Germplasm collection where each item in the array is - Name, Accession, Genus, Species and Origin (Country of origin).
```suggestion
 *   Germplasm collection where each item in the array is - Name, Accession, Entity ID, Genus, Species and Origin (Country of origin).
```

The entity_id is added to the results on ln49 so adding it to the documentation.

2022-03-04 20:13 UTC, laceysanderson commented on germcollection/api/germcollection.api.inc
> +  $m = db_query('SELECT t2.name
```suggestion
  // Retrieves the name of the Tripal bundle based on the stock type_id
  $m = db_query('SELECT t2.name
```

2022-03-04 20:13 UTC, laceysanderson commented on germcollection/api/germcollection.api.inc
> +    $sql = sprintf('SELECT t1.entity_id FROM %s AS t1 INNER JOIN {stock} AS t2 ON t1.record_id = t2.stock_id
This is an unnecessarily long/slow query. You can skip the inner join here and just say `t1.record_id = :stock_id`.

2022-04-13 22:54 UTC, laceysanderson requested changes
Items from my original review:
- [x] comment additions
- [x] remove inner join on query for performance reasons
- [ ] add germplasm collection name + link to page in field
- [ ] always show name + number of germplasm regardless of permission. If no permission then the list and download link are not shown.

So it looks like the last two items were not done yet?

> add germplasm collection name + link to page in field

We want the name of the germplasm collection with a link to its page provided in This Field -specifically through the formatted. Currently you see the name in the page due to the following field which just provides a textfield for a projectprop entry. This is clearly not ideal and we want to remove the chado property field completely.
<img width="1129" alt="Screen Shot 2022-04-13 at 4 48 32 PM" src="https://user-images.githubusercontent.com/1566301/163282463-87dcaa4a-be33-407b-b125-0477d4272adc.png">

To do that though your field needs to have the collection name with a link to the collection page. My original field did have this but you removed it... It's still stored in the `$link` variable that you no longer use.

> always show name + number of germplasm regardless of permission. If no permission then the list and download link are not shown.

Right now line 91 of the formatted ensures the field shows "Germplasm collection not available" if people do not have permission to see germplasm. However, it should still show the information in `$field_markup` but with $download_link and $summary_tables removed. **The germplasm collection name/link and germplasm count should ALWAYS SHOW regardless of permission.**

2022-04-20 20:50 UTC, reynoldtan commented
Revised field as describe. Tested:

- [x] user given permission ✔️ 
- [x] user has no permission ✖️ 
- [x] anonymous user ✖️ 

![image](https://user-images.githubusercontent.com/15472253/164319308-c669ee94-074b-4f9d-9c4f-1dd173784fa6.png)

2022-06-24 22:38 UTC, laceysanderson approved these changes
Changes look good! I am merging thus but we shouldn't make it live until July just to ensure nothing goes wrong right before the workshop ;-p

2022-06-24 22:38 UTC, merged